[package]
name = "paver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26.1"
ash = "0.37.0"
ash-window = "0.10.0"
bytemuck = "1.9.1"
serde = "1.0.137"
termcolor = "1.1.3"
